# Generated by Django 4.2.7 on 2023-11-14 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
